[W 2022-08-11 09:32:03.887 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-08-11 09:32:03.887 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-08-11 09:32:03.887 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-08-11 09:32:03.887 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-08-11 09:32:03.890 LabApp] JupyterLab extension loaded from /home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/jupyterlab
[I 2022-08-11 09:32:03.891 LabApp] JupyterLab application directory is /home/fs02/pmr82_0001/ah986/rival_framings/share/jupyter/lab
[I 09:32:03.895 NotebookApp] Serving notebooks from local directory: /home/fs02/pmr82_0001/ah986/drought_classification
[I 09:32:03.895 NotebookApp] Jupyter Notebook 6.4.5 is running at:
[I 09:32:03.895 NotebookApp] http://localhost:18180/?token=34a3844969f63e60485da1d5bf613b38ef398bc785ce68cb
[I 09:32:03.895 NotebookApp]  or http://127.0.0.1:18180/?token=34a3844969f63e60485da1d5bf613b38ef398bc785ce68cb
[I 09:32:03.895 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:32:03.901 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/fs02/pmr82_0001/ah986/.local/share/jupyter/runtime/nbserver-2551599-open.html
    Or copy and paste one of these URLs:
        http://localhost:18180/?token=34a3844969f63e60485da1d5bf613b38ef398bc785ce68cb
     or http://127.0.0.1:18180/?token=34a3844969f63e60485da1d5bf613b38ef398bc785ce68cb
[I 09:34:17.746 NotebookApp] 302 GET /?token=34a3844969f63e60485da1d5bf613b38ef398bc785ce68cb (::1) 0.510000ms
[W 09:34:25.790 NotebookApp] Notebook hive_plots_drought_impacts.ipynb is not trusted
[W 09:34:25.811 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20220811093203 (::1) 6.840000ms referer=http://localhost:8888/notebooks/hive_plots_drought_impacts.ipynb
[I 09:34:26.280 NotebookApp] Kernel started: 1231c968-9f6e-480f-a86d-807e0592472f, name: python3
Exception in callback <TaskStepMethWrapper object at 0x1534085d5048>()
handle: <Handle <TaskStepMethWrapper object at 0x1534085d5048>()>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
KeyError: <_UnixSelectorEventLoop running=True closed=False debug=False>
[I 09:38:26.357 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[W 09:38:26.357 NotebookApp] Notebook hive_plots_drought_impacts.ipynb is not trusted
[I 09:40:26.923 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[W 09:40:26.923 NotebookApp] Notebook hive_plots_drought_impacts.ipynb is not trusted
[I 09:42:26.698 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[W 09:42:26.698 NotebookApp] Notebook hive_plots_drought_impacts.ipynb is not trusted
[I 09:44:26.479 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 09:46:26.573 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 09:48:26.699 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[W 09:49:55.361 NotebookApp] Notebook streamflow_distribution_changes.ipynb is not trusted
[W 09:49:55.377 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20220811093203 (::1) 2.810000ms referer=http://localhost:8888/notebooks/streamflow_distribution_changes.ipynb
[I 09:49:56.062 NotebookApp] Kernel started: 54f60ec7-58b0-47de-b87d-03e832ace271, name: python3
[I 09:52:26.595 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 09:54:26.515 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 09:56:26.692 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 09:58:26.569 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:00:27.631 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:04:26.765 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:06:26.612 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:08:26.759 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:10:26.639 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:12:26.597 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:14:26.610 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:16:27.437 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:18:26.738 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/ipykernel/kernelbase.py", line 579, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/home/fs02/pmr82_0001/ah986/rival_framings/lib64/python3.6/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'
[I 10:20:27.134 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:22:27.043 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:24:27.017 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:26:26.498 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:28:26.698 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:32:27.273 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 10:34:26.560 NotebookApp] Saving file at /hive_plots_drought_impacts.ipynb
[I 12:58:37.125 NotebookApp] Starting buffering for 54f60ec7-58b0-47de-b87d-03e832ace271:4a9856a69d9e436e99893af928c37db6
[I 12:58:37.166 NotebookApp] Starting buffering for 1231c968-9f6e-480f-a86d-807e0592472f:76b59856219146a8866be6cea27027dd
[I 12:58:38.368 NotebookApp] Restoring connection for 1231c968-9f6e-480f-a86d-807e0592472f:76b59856219146a8866be6cea27027dd
[I 12:58:38.518 NotebookApp] Restoring connection for 54f60ec7-58b0-47de-b87d-03e832ace271:4a9856a69d9e436e99893af928c37db6
[W 13:02:38.369 NotebookApp] WebSocket ping timeout after 119802 ms.
[W 13:02:38.519 NotebookApp] WebSocket ping timeout after 119946 ms.
[I 13:02:43.373 NotebookApp] Starting buffering for 1231c968-9f6e-480f-a86d-807e0592472f:76b59856219146a8866be6cea27027dd
[I 13:02:43.520 NotebookApp] Starting buffering for 54f60ec7-58b0-47de-b87d-03e832ace271:4a9856a69d9e436e99893af928c37db6
[I 13:03:23.631 NotebookApp] Restoring connection for 54f60ec7-58b0-47de-b87d-03e832ace271:4a9856a69d9e436e99893af928c37db6
[I 13:03:23.769 NotebookApp] Restoring connection for 1231c968-9f6e-480f-a86d-807e0592472f:76b59856219146a8866be6cea27027dd
[W 13:10:23.632 NotebookApp] WebSocket ping timeout after 119814 ms.
[W 13:10:23.770 NotebookApp] WebSocket ping timeout after 119945 ms.
[I 13:10:28.636 NotebookApp] Starting buffering for 54f60ec7-58b0-47de-b87d-03e832ace271:4a9856a69d9e436e99893af928c37db6
[I 13:10:28.772 NotebookApp] Starting buffering for 1231c968-9f6e-480f-a86d-807e0592472f:76b59856219146a8866be6cea27027dd
slurmstepd: error: *** STEP 21178.0 ON c0001 CANCELLED AT 2022-08-11T17:32:11 DUE TO TIME LIMIT ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 21178 ON c0001 CANCELLED AT 2022-08-11T17:32:11 DUE TO TIME LIMIT ***
srun: got SIGCONT
srun: forcing job termination
